using System;
using System.IO;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class SettingsManager : MonoBehaviour
{
    // dictionaries for iterating through values easier
    // default values
    private static Dictionary<string, object> _defaultValues = new Dictionary<string, object>()
    {
        ["Controller Frequency"] = 50, // this is the same frequency as the default physics update speed in unity
        ["Trial Duration"] = 100, // how long each game will last
        ["Ramp Duration"] = 1.0f, // how long it takes to ramp up to 100% stimulation when the target changes
        ["Max A/P Fraction"] = 18.0926f, // can be removed, unnecessary
        ["Ankle Fraction"] = 2.0f, // percentage of total height that corresponds to the distance between heel to ankle
        ["Number of Trials"] = 2, // how many times the experiment will be run
        ["Filter Order"] = 2, // order of the moving average/butterworth filter
        ["Length Offset"] = 0.0f, // measure of how far the quiet standing centre of pressure is from the 0,0 of the board (ie. the centre)
        ["Star Multiplier"] = 120, // used for the unimplemented star game
        ["Config Root Path"] = Directory.GetCurrentDirectory(), // where any files generated by the program are stored
        ["Rolling Average Window"] = 1, // window used to calculate the average max excursion for los
        ["RPF Max"] = 50, // maximum stimulation for rpf
        ["RDF Max"] = 50, // maximum stimulation for rdf
        ["LPF Max"] = 50, // maximum stimulation for lpf
        ["LDF Max"] = 50, // maximum stimulation for ldf
        ["Height"] = 170, // height in cm
        ["Mass"] = 65f, //mass in kilos
        ["Ankle Mass Fraction"] = 0.971f, // mass of body without feet
        ["CoM Height"] = 0.547f, // height of com relative to total height
        ["Inertia Coefficient"] = 0.319f, // coefficient to calculate the inertia
        ["Kp Coefficient"] = 0.24432f, // coefficient of mgh_com to calculate Kp
        ["Kd Coefficient"] = 0.22418f, // coefficient of mgh_com to calculate Kd
        ["K Coefficient"] = 0.75024f, // coefficient of mgh_com to calculate K for mechnical controller
        ["Duration of Target"] = 10f, // how long the target lasts
        ["Duration to Get Points"] = 3f, // how long participants need to stay in the target to get the points
        ["Limit of Stability Front"] = 1f, // percentage of board, how far the participant can reach in the four directions, default needs to be one, if zero then it's a divide by zero error
        ["Limit of Stability Back"] = 1f, 
        ["Limit of Stability Left"] = 1f,
        ["Limit of Stability Right"] = 1f,
    };
    private static Dictionary<string, InputField> _fields = new Dictionary<string, InputField>();
    public static Dictionary<string, string> _fieldNamesAndTypes = new Dictionary<string, string>() 
    {
        ["Controller Frequency"] = "int",
        ["Trial Duration"] = "int",
        ["Ramp Duration"] = "float",
        ["Max A/P Fraction"] = "float",
        ["Ankle Fraction"] = "float",
        ["Number of Trials"] = "int",
        ["Filter Order"] = "int",
        ["Length Offset"] = "float",
        ["Star Multiplier"] = "int",
        ["Config Root Path"] = "string",
        ["Rolling Average Window"] = "int",
        ["RPF Max"] = "int",
        ["RDF Max"] = "int",
        ["LPF Max"] = "int",
        ["LDF Max"] = "int",
        ["Height"] = "int",
        ["Mass"] = "float",
        ["Ankle Mass Fraction"] = "float",
        ["CoM Height"] = "float",
        ["Inertia Coefficient"] = "float",
        ["Kp Coefficient"] = "float",
        ["Kd Coefficient"] = "float",
        ["K Coefficient"] = "float",
        ["Duration of Target"] = "float",
        ["Duration to Get Points"] = "float",
        ["Limit of Stability Front"] = "float",
        ["Limit of Stability Back"] = "float",
        ["Limit of Stability Left"] = "float",
        ["Limit of Stability Right"] = "float"
    };

    private void Awake() 
    {
        if (SceneManager.GetActiveScene().buildIndex == 0) //only do this at the start screen
        {
            foreach (var nameAndType in _fieldNamesAndTypes)
            {
                if (!PlayerPrefs.HasKey(nameAndType.Key)) //if opening up game for first time, set all values to default, missing values also set to default
                {
                    if (nameAndType.Value == "int")
                        PlayerPrefs.SetInt(nameAndType.Key, (int)_defaultValues[nameAndType.Key]);
                    else if (nameAndType.Value == "float")
                        PlayerPrefs.SetFloat(nameAndType.Key, (float)_defaultValues[nameAndType.Key]);
                    else
                        PlayerPrefs.SetString(nameAndType.Key, (string)_defaultValues[nameAndType.Key]);
                }
            }
        }
    }

    public void SetInputFields() 
    {
        _fields.Clear(); //because objects get refreshed every time scene is reloaded, need to add "new" fields to dictionary

        var fields = FindObjectsOfType<InputField>(); //array form, want to conver to dictionary instead - easier to work with

        foreach (var field in fields)
            _fields.Add(field.name, field);

        SetInputs();
    }

    public void SaveSettings()
    {
        foreach (var nameAndType in _fieldNamesAndTypes) //saves new set values
        {
            if (nameAndType.Value == "int")
                PlayerPrefs.SetInt(nameAndType.Key, Convert.ToInt32(_fields[nameAndType.Key].text));
            else if (nameAndType.Value == "float")
                PlayerPrefs.SetFloat(nameAndType.Key, float.Parse(_fields[nameAndType.Key].text));
            else 
            {
                if (Directory.Exists(_fields[nameAndType.Key].text))
                    PlayerPrefs.SetString(nameAndType.Key, _fields[nameAndType.Key].text);
                else
                    _fields["Info"].text = "Config path doesn't exist. Please provide a valid path";
            }
        }

        PlayerPrefs.Save();
    }

    public void ResetToDefaults()
    {
        PlayerPrefs.DeleteAll();
        SetInputs();
    }

    //toggles are saved separately
    public void ZeroBoard() 
    {
        var isChecked = GameObject.Find("Zero Board").GetComponent<Toggle>().isOn;

        if (isChecked)
            PlayerPrefs.SetInt("Zero Board", 1);
        else
            PlayerPrefs.SetInt("Zero Board", 0);
    }

    public void FilterData()
    {
        var isChecked = GameObject.Find("Filter Data").GetComponent<Toggle>().isOn;

        if (isChecked)
            PlayerPrefs.SetInt("Filter Data", 1);
        else
            PlayerPrefs.SetInt("Filter Data", 0);
    }

    public void ECOrEO()
    {
        var isChecked = GameObject.Find("Eyes Condition").GetComponent<Toggle>().isOn;

        if (isChecked)
            PlayerPrefs.SetInt("EC or EO", 1);
        else
            PlayerPrefs.SetInt("EC or EO", 0);
    }

    private void SetInputs()
    {
        foreach (var nameAndType in _fieldNamesAndTypes)
        {
            if (nameAndType.Value == "int")
                _fields[nameAndType.Key].text = PlayerPrefs.GetInt(nameAndType.Key, (int)_defaultValues[nameAndType.Key]).ToString();
            else if (nameAndType.Value == "float")
                _fields[nameAndType.Key].text = PlayerPrefs.GetFloat(nameAndType.Key, (float)_defaultValues[nameAndType.Key]).ToString();
            else
                _fields[nameAndType.Key].text = PlayerPrefs.GetString(nameAndType.Key, (string)_defaultValues[nameAndType.Key]).ToString();

            if (!PlayerPrefs.HasKey(nameAndType.Key)) //sets to default values if the keys don't current exist
            {
                if (nameAndType.Value == "int")
                    PlayerPrefs.SetInt(nameAndType.Key, (int)_defaultValues[nameAndType.Key]);
                else if (nameAndType.Value == "float")
                    PlayerPrefs.SetFloat(nameAndType.Key, (float)_defaultValues[nameAndType.Key]);
                else
                    PlayerPrefs.SetString(nameAndType.Key, (string)_defaultValues[nameAndType.Key]);
            }
        }

        var toggles = FindObjectsOfType<Toggle>();

        foreach (var toggle in toggles)
        {
            if (toggle.name == "Zero Board")
                toggle.GetComponent<Toggle>().isOn = Convert.ToBoolean(PlayerPrefs.GetInt("Zero Board"));
            else if (toggle.name == "Filter Data")
                toggle.GetComponent<Toggle>().isOn = Convert.ToBoolean(PlayerPrefs.GetInt("Filter Data"));
            else if (toggle.name == "Eyes Condition")
                toggle.GetComponent<Toggle>().isOn = Convert.ToBoolean(PlayerPrefs.GetInt("EC or EO"));
        }
    }
}